# アプリーション名
spring.application.name=Schedule

# ポート番号
server.port=9999

# DB接続用ドライバー
spring.datasource.driverClassName=org.h2.Driver

# DBの保存先（C:\Users\ユーザー\db.mv.db）
spring.datasource.url=jdbc:h2:~/db
spring.datasource.username=SA
spring.datasource.password=

# schema.sql と data.sql を実行
spring.sql.init.mode=always

# Hibernateによるテーブル自動操作を無効化
spring.jpa.hibernate.ddl-auto=none

# SQLログをコンソールに出力しない
spring.jpa.show-sql=false

# DBアクセスをService層に限定
spring.jpa.open-in-view=false